### ISSUE TITLE
liferay can't be started

### ISSUE THREAD

**Issue by tiurlumbangaol** [cetic/ansible-role-liferay#1]
after running it, it's showing : 
TASK [cetic.liferay : wait for liferay startup] ********************************
FAILED - RETRYING: wait for liferay startup (1000 retries left).
FAILED - RETRYING: wait for liferay startup (999 retries left).
FAILED - RETRYING: wait for liferay startup (998 retries left).
FAILED - RETRYING: wait for liferay startup (997 retries left).
FAILED - RETRYING: wait for liferay startup (996 retries left).
FAILED - RETRYING: wait for liferay startup (995 retries left).
FAILED - RETRYING: wait for liferay startup (994 retries left).
FAILED - RETRYING: wait for liferay startup (993 retries left).
FAILED - RETRYING: wait for liferay startup (992 retries left).
FAILED - RETRYING: wait for liferay startup (991 retries left).
FAILED - RETRYING: wait for liferay startup (990 retries left).
FAILED - RETRYING: wait for liferay startup (989 retries left).

nothing is there on log, no error log. it's simply freeze.

please help...

**Comment by alexnuttinck** [comment]
Hi,

I think it's normal. See the Travis logs: https://travis-ci.org/cetic/ansible-role-liferay. 
The time needed to liferay to start is not insignificant.

You can follow the setup of Liferay in the logs: 'opt/liferay/tomcat/logs/catalina.out'
