### ISSUE TITLE
Does it work with Liferay 7.1

### ISSUE THREAD

**Issue by jjaone** [cetic/ansible-role-liferay#2]
Is your Ansible-play compatible with Liferay 7.1 ?
What version of Java and Ansible is required?

**Comment by alexnuttinck** [comment]
Hi @jjaone, 
Never tested yet.
I add a Vagrant file, so you can test locally the ansible playbook with the Liferay version of your choice. (https://github.com/cetic/ansible-role-liferay#tests) 
Don't hesitate to make a pull request with a more recent of Liferay.

For the java version, I use the openjdk ansible role by Geerlingguy. It installs the version 1.8. See the example playbook: https://github.com/cetic/ansible-role-liferay#example-playbook

For the ansible version, at least 2.2 should be OK.

**Comment by alexnuttinck** [comment]
I close this issue as there is no feedback. Please, feel free to reopen.
